import { writeFileSync } from 'fs'

const t = []
const p = (s) => t.push(s)

p("import { describe, it, expect, vi, beforeEach } from 'vitest'")
p("import type { Room, Hallway, Building, Floor } from '@navi/core'")
p("import type { LocalCoord, LocalPolygon, LocalPolyline } from '@navi/core'")
p("import { renderWalls2_5d, renderFloor2_5d, apply2_5dTransform, reset2_5dTransform, roomsToWalls2_5d, roomsToFloors2_5d, hallwaysToWalls2_5d, buildingToWalls2_5d, buildingToFloors2_5d, DEFAULT_STYLE_2_5D, type Wall2_5d, type Floor2_5d, type Style2_5d, } from '../renderer-2_5d'")
p("")
p("function createMockCtx(): CanvasRenderingContext2D { return { save: vi.fn(), restore: vi.fn(), beginPath: vi.fn(), moveTo: vi.fn(), lineTo: vi.fn(), closePath: vi.fn(), fill: vi.fn(), stroke: vi.fn(), fillStyle: '', strokeStyle: '', lineWidth: 1, shadowOffsetX: 0, shadowOffsetY: 0, shadowBlur: 0, shadowColor: '', rotate: vi.fn(), scale: vi.fn(), } as unknown as CanvasRenderingContext2D }")
p("function makeLocalCoord(x: number, y: number): LocalCoord { return { x, y } }")
p("function makeRoom(id: string, points: LocalCoord[], category = 'classroom'): Room { return { id, name: `Room ${id}`, number: '101', category: category as any, polygon: { points: [...points, points[0]] } as LocalPolygon, roomDoors: [], capacity: 30, metadata: {} } }")
p("function makeHallway(id: string, points: LocalCoord[], width = 2): Hallway { return { id, name: `Hallway ${id}`, polyline: { points } as LocalPolyline, width } }")
p("")
p("describe('renderer-2_5d', () => {")
p("  let ctx: CanvasRenderingContext2D")
p("  beforeEach(() => { ctx = createMockCtx() })")
p("")
p("  describe('apply2_5dTransform', () => {")
p("    it('calls save, rotate, and scale', () => {")
p("      apply2_5dTransform(ctx, 30, 0)")
p("      expect(ctx.save).toHaveBeenCalledOnce()")
p("      expect(ctx.rotate).toHaveBeenCalledOnce()")
p("      expect(ctx.scale).toHaveBeenCalledOnce()")
p("      const rotateAngle = (ctx.rotate as any).mock.calls[0][0]")
p("      expect(rotateAngle).toBeCloseTo(0)")
p("      const [scaleX, scaleY] = (ctx.scale as any).mock.calls[0]")
p("      expect(scaleX).toBeCloseTo(Math.cos((30 * Math.PI) / 180))")
p("      expect(scaleY).toBeCloseTo(Math.cos((30 * Math.PI) / 180) * 0.6)")
p("    })")
p("    it('applies rotation when tilt is 0', () => {")
p("      apply2_5dTransform(ctx, 0, 45)")
p("      const rotateAngle = (ctx.rotate as any).mock.calls[0][0]")
p("      expect(rotateAngle).toBeCloseTo(-(45 * Math.PI) / 180)")
p("    })")
p("    it('combines tilt and rotation', () => {")
p("      apply2_5dTransform(ctx, 45, 90)")
p("      const rotateAngle = (ctx.rotate as any).mock.calls[0][0]")
p("      expect(rotateAngle).toBeCloseTo(-(90 * Math.PI) / 180)")
p("      const expectedTiltRad = (45 * Math.PI) / 180")
p("      const [scaleX, scaleY] = (ctx.scale as any).mock.calls[0]")
p("      expect(scaleX).toBeCloseTo(Math.cos(expectedTiltRad))")
p("      expect(scaleY).toBeCloseTo(Math.cos(expectedTiltRad) * 0.6)")
p("    })")
p("  })")
p("  describe('reset2_5dTransform', () => {")
p("    it('calls restore', () => { reset2_5dTransform(ctx); expect(ctx.restore).toHaveBeenCalledOnce() })")
p("  })")
p("  describe('roomsToWalls2_5d', () => {")
p("    it('extracts wall segments from room polygons', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const walls = roomsToWalls2_5d([room], 3.5)")
p("      expect(walls).toHaveLength(4)")
p("      expect(walls[0].id).toBe('room-1-wall-0')")
p("      expect(walls[0].points).toHaveLength(2)")
p("      expect(walls[0].height).toBe(3.5)")
p("    })")
p("    it('skips rooms with fewer than 3 points', () => {")
p("      const room = makeRoom('room-1', [])")
p("      expect(roomsToWalls2_5d([room], 3.5)).toHaveLength(0)")
p("    })")
p("    it('handles multiple rooms', () => {")
p("      const r1 = makeRoom('r1', [makeLocalCoord(0,0), makeLocalCoord(5,0), makeLocalCoord(5,5), makeLocalCoord(0,5)])")
p("      const r2 = makeRoom('r2', [makeLocalCoord(6,0), makeLocalCoord(11,0), makeLocalCoord(11,5), makeLocalCoord(6,5)])")
p("      expect(roomsToWalls2_5d([r1, r2], 3.5)).toHaveLength(8)")
p("    })")
p("    it('uses style wall color', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const walls = roomsToWalls2_5d([room], 3.5, { ...DEFAULT_STYLE_2_5D, wallColor: '#FF0000' })")
p("      expect(walls[0].color).toBe('#FF0000')")
p("    })")
p("  })")
p("  describe('roomsToFloors2_5d', () => {")
p("    it('extracts floor polygons', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const floors = roomsToFloors2_5d([room])")
p("      expect(floors).toHaveLength(1)")
p("      expect(floors[0].id).toBe('room-1')")
p("      expect(floors[0].points.length).toBeGreaterThanOrEqual(3)")
p("    })")
p("    it('uses style floor color', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const floors = roomsToFloors2_5d([room], { ...DEFAULT_STYLE_2_5D, floorColor: '#00FF00' })")
p("      expect(floors[0].color).toBe('#00FF00')")
p("    })")
p("  })")
p("  describe('hallwaysToWalls2_5d', () => {")
p("    it('creates left and right walls', () => {")
p("      const hw = makeHallway('hw-1', [makeLocalCoord(0,0), makeLocalCoord(10,0)])")
p("      const walls = hallwaysToWalls2_5d([hw], 3.5)")
p("      expect(walls).toHaveLength(2)")
p("      expect(walls[0].id).toBe('hw-1-wall-left')")
p("      expect(walls[1].id).toBe('hw-1-wall-right')")
p("    })")
p("    it('handles multi-segment hallways', () => {")
p("      const hw = makeHallway('hw-1', [makeLocalCoord(0,0), makeLocalCoord(5,0), makeLocalCoord(5,5), makeLocalCoord(10,5)])")
p("      const walls = hallwaysToWalls2_5d([hw], 3.5)")
p("      expect(walls).toHaveLength(2)")
p("      expect(walls[0].points.length).toBeGreaterThanOrEqual(2)")
p("    })")
p("    it('skips hallways with fewer than 2 points', () => {")
p("      const hw = makeHallway('hw-1', [makeLocalCoord(0,0)])")
p("      expect(hallwaysToWalls2_5d([hw], 3.5)).toHaveLength(0)")
p("    })")
p("  })")
p("  describe('buildingToWalls2_5d', () => {")
p("    it('combines room and hallway walls', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const hw = makeHallway('hw-1', [makeLocalCoord(5,0), makeLocalCoord(5,10)])")
p("      const bld = { id: 'bld-1', name: 'Test', code: 'TB', category: 'academic', description: '', footprint: { points: [] }, baseElevation: 0, height: 20, color: '#4A90D9', floors: [], aliases: [], metadata: {} } as unknown as Building")
p("      const floor = { id: 'f1', level: 0, label: 'Ground', elevation: 0, height: 3.5, rooms: [room], hallways: [hw], staircases: [], elevators: [], entrances: [], connectorStops: [], parametricComponents: [], metadata: {} } as unknown as Floor")
p("      expect(buildingToWalls2_5d(bld, floor)).toHaveLength(6)")
p("    })")
p("  })")
p("  describe('buildingToFloors2_5d', () => {")
p("    it('extracts floor polygons', () => {")
p("      const room = makeRoom('room-1', [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)])")
p("      const bld = { id: 'bld-1', name: 'Test' } as unknown as Building")
p("      const floor = { id: 'f1', level: 0, label: 'Ground', elevation: 0, height: 3.5, rooms: [room], hallways: [], metadata: {} } as unknown as Floor")
p("      const floors = buildingToFloors2_5d(bld, floor)")
p("      expect(floors).toHaveLength(1)")
p("      expect(floors[0].points.length).toBeGreaterThanOrEqual(3)")
p("    })")
p("  })")
p("  describe('renderWalls2_5d', () => {")
p("    it('calls Canvas 2D methods', () => {")
p("      const walls: Wall2_5d[] = [{ id: 'w1', points: [{x:0,y:0},{x:10,y:0}], height: 3.5, color: '#4A90D9', opacity: 0.85 }]")
p("      renderWalls2_5d(ctx, walls)")
p("      expect(ctx.save).toHaveBeenCalledOnce()")
p("      expect(ctx.restore).toHaveBeenCalledOnce()")
p("      expect(ctx.beginPath).toHaveBeenCalled()")
p("      expect(ctx.fill).toHaveBeenCalled()")
p("      expect(ctx.stroke).toHaveBeenCalled()")
p("    })")
p("    it('renders multiple walls', () => {")
p("      const walls: Wall2_5d[] = [{ id: 'w1', points: [{x:0,y:0},{x:10,y:0}], height: 3.5, color: '#4A90D9', opacity: 0.85 }, { id: 'w2', points: [{x:10,y:0},{x:10,y:10}], height: 3.5, color: '#4A90D9', opacity: 0.85 }]")
p("      renderWalls2_5d(ctx, walls)")
p("      expect(ctx.beginPath).toHaveBeenCalledTimes(2)")
p("      expect(ctx.fill).toHaveBeenCalledTimes(2)")
p("    })")
p("    it('skips walls with fewer than 2 points', () => {")
p("      renderWalls2_5d(ctx, [{ id: 'w1', points: [{x:0,y:0}], height: 3.5, color: '#4A90D9', opacity: 0.85 }])")
p("      expect(ctx.beginPath).not.toHaveBeenCalled()")
p("    })")
p("  })")
p("  describe('renderFloor2_5d', () => {")
p("    it('calls Canvas 2D methods', () => {")
p("      const floors: Floor2_5d[] = [{ id: 'f1', points: [{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}], color: '#87CEEB', opacity: 0.4 }]")
p("      renderFloor2_5d(ctx, floors)")
p("      expect(ctx.save).toHaveBeenCalledOnce()")
p("      expect(ctx.restore).toHaveBeenCalledOnce()")
p("      expect(ctx.beginPath).toHaveBeenCalled()")
p("      expect(ctx.fill).toHaveBeenCalled()")
p("      expect(ctx.stroke).toHaveBeenCalled()")
p("    })")
p("    it('skips floors with fewer than 3 points', () => {")
p("      renderFloor2_5d(ctx, [{ id: 'f1', points: [{x:0,y:0},{x:10,y:0}], color: '#87CEEB', opacity: 0.4 }])")
p("      expect(ctx.beginPath).not.toHaveBeenCalled()")
p("    })")
p("  })")
p("  describe('same geometry as 2D renderer', () => {")
p("    it('roomsToWalls2_5d produces walls matching room polygon edges', () => {")
p("      const points: LocalCoord[] = [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)]")
p("      const room = makeRoom('room-1', points)")
p("      const walls = roomsToWalls2_5d([room], 3.5)")
p("      expect(walls).toHaveLength(points.length)")
p("      for (let i = 0; i < points.length; i++) {")
p("        const wall = walls[i]")
p("        expect(wall.points[0]).toEqual(points[i])")
p("        expect(wall.points[1]).toEqual(points[(i + 1) % points.length])")
p("      }")
p("    })")
p("    it('roomsToFloors2_5d produces floor matching room polygon', () => {")
p("      const points: LocalCoord[] = [makeLocalCoord(0,0), makeLocalCoord(10,0), makeLocalCoord(10,10), makeLocalCoord(0,10)]")
p("      const room = makeRoom('room-1', points)")
p("      const floors = roomsToFloors2_5d([room])")
p("      expect(floors).toHaveLength(1)")
p("      expect(floors[0].points).toEqual(room.polygon.points)")
p("    })")
p("    it('hallwaysToWalls2_5d walls are offset from polyline by half width', () => {")
p("      const hw = makeHallway('hw-1', [makeLocalCoord(0,0), makeLocalCoord(10,0)], 4)")
p("      const walls = hallwaysToWalls2_5d([hw], 3.5)")
p("      expect(walls).toHaveLength(2)")
p("      const leftWall = walls.find(w => w.id.includes('left'))!")
p("      const rightWall = walls.find(w => w.id.includes('right'))!")
p("      const leftY = leftWall.points[0].y")
p("      const rightY = rightWall.points[0].y")
p("      expect(Math.abs(leftY)).toBe(2)")
p("      expect(Math.abs(rightY)).toBe(2)")
p("      expect(leftY).not.toBe(rightY)")
p("    })")
p("  })")
p("  describe('DEFAULT_STYLE_2_5d', () => {")
p("    it('has valid default values', () => {")
p("      expect(DEFAULT_STYLE_2_5D.wallColor).toMatch(/^#[0-9A-F]{6}$/i)")
p("      expect(DEFAULT_STYLE_2_5D.wallOpacity).toBeGreaterThan(0)")
p("      expect(DEFAULT_STYLE_2_5D.wallOpacity).toBeLessThanOrEqual(1)")
p("      expect(DEFAULT_STYLE_2_5D.floorColor).toMatch(/^#[0-9A-F]{6}$/i)")
p("      expect(DEFAULT_STYLE_2_5D.floorOpacity).toBeGreaterThan(0)")
p("      expect(DEFAULT_STYLE_2_5D.floorOpacity).toBeLessThanOrEqual(1)")
p("      expect(DEFAULT_STYLE_2_5D.wallHeight).toBeGreaterThan(0)")
p("      expect(DEFAULT_STYLE_2_5D.strokeWidth).toBeGreaterThan(0)")
p("    })")
p("  })")
p("})")

writeFileSync('renderer-2_5d.test.ts', t.join('\n') + '\n')
writeFileSync('gen-test.mjs.done', 'ok')
