export type { GraphValidationRule, GraphValidationContext, ValidationReport, ValidationStatistics } from './types'
export { GraphValidator, buildContext } from './validator'
export { DuplicateNodeRule } from './graph/duplicate-nodes'
export { DuplicateEdgeRule } from './graph/duplicate-edges'
export { MissingNodeRefRule, ZeroWeightRule } from './graph/edge-integrity'
export { DisconnectedGraphRule } from './graph/connectivity'
export { UnreachableRoomRule } from './graph/unreachable-room'
export { MissingEntranceRule } from './graph/missing-entrance'
export { DuplicateCoordsRule } from './graph/duplicate-coords'
